### ISSUE TITLE
Electron example not working

### ISSUE THREAD

**Issue by davej** [queelag/fcm#12]
After populating the `.env` file and running `pnpm i` and `pnpm start` I get the following error:

```
An unhandled rejection has occurred inside Forge:
Error [ERR_REQUIRE_ESM]: require() of ES Module electron/node_modules/log-update/node_modules/ansi-styles/index.js from electron/node_modules/log-update/node_modules/slice-ansi/index.js not supported.
Instead change the require of electron/node_modules/log-update/node_modules/ansi-styles/index.js in electron/node_modules/log-update/node_modules/slice-ansi/index.js to a dynamic import() which is available in all CommonJS modules.

An unhandled rejection has occurred inside Forge:
Error [ERR_REQUIRE_ESM]: require() of ES Module electron/node_modules/log-update/node_modules/ansi-styles/index.js from electron/node_modules/log-update/node_modules/slice-ansi/index.js not supported.
Instead change the require of electron/node_modules/log-update/node_modules/ansi-styles/index.js in electron/node_modules/log-update/node_modules/slice-ansi/index.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (electron/node_modules/log-update/node_modules/slice-ansi/index.js:4:20)
    at async _DefaultRenderer.render (electron/node_modules/listr2/dist/index.cjs:761:33)
    at async _Listr.run (electron/node_modules/listr2/dist/index.cjs:2208:5)
    at async electron/node_modules/@electron-forge/cli/dist/electron-forge.js:58:5
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by alchemicas** [comment]
Hello @davej , thanks for the report, I will take a look in the next days.

**Comment by 4br3mm0rd** [comment]
Hey,

I just tried to play with it and it work for me using `npm run` instead of `pnpm`
